<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Assets\" />
    <Folder Include="Root Desk\Desktop\" />
    <Folder Include="Root Desk\Downloads\" />
    <Folder Include="Root Desk\Documents\" />
    <Folder Include="Root Desk\Pictures\Camera\" />
    <Folder Include="Root Desk\Pictures\Saved Pictures\" />
  </ItemGroup>

</Project>
